import {cardFixture} from './harness.ts';

export interface ToolCase {
  name: string;
  args: Record<string, unknown>;
  method: string;
  path: string;
  query?: Record<string, string>;
  body?: unknown;
  response: unknown;
}

const page = {limit: '25', offset: '0'};
const entity = {id: 1, title: 'Workspace', name: 'Name'};
const card = {card_id: 10};
const checklist = {...card, checklist_id: 8};
export const directoryId = '12345678-1234-4234-8234-123456789abc';

export const toolCases: ToolCase[] = [
  {
    name: 'list_spaces',
    args: {},
    method: 'GET',
    path: '/spaces',
    query: page,
    response: [entity],
  },
  {
    name: 'get_space',
    args: {space_id: 1},
    method: 'GET',
    path: '/spaces/1',
    response: entity,
  },
  {
    name: 'list_boards',
    args: {space_id: 1},
    method: 'GET',
    path: '/spaces/1/boards',
    response: [entity],
  },
  {
    name: 'get_board',
    args: {board_id: 2},
    method: 'GET',
    path: '/boards/2',
    response: {...entity, columns: [], lanes: []},
  },
  {
    name: 'list_columns',
    args: {board_id: 2},
    method: 'GET',
    path: '/boards/2/columns',
    response: [entity],
  },
  {
    name: 'list_lanes',
    args: {board_id: 2},
    method: 'GET',
    path: '/boards/2/lanes',
    response: [entity],
  },
  {
    name: 'get_current_user',
    args: {},
    method: 'GET',
    path: '/users/current',
    response: {id: 5, full_name: 'User'},
  },
  {
    name: 'list_users',
    args: {query: 'User'},
    method: 'GET',
    path: '/company/users',
    query: {...page, query: 'User'},
    response: [{id: 5, full_name: 'User'}],
  },
  {
    name: 'list_card_types',
    args: {},
    method: 'GET',
    path: '/card-types',
    query: page,
    response: [entity],
  },
  {
    name: 'list_tags',
    args: {space_id: 1, query: 'Tag'},
    method: 'GET',
    path: '/tags',
    query: {...page, space_id: '1', query: 'Tag'},
    response: [entity],
  },
  {
    name: 'search_cards',
    args: {query: 'A card', member_ids: [5, 6], states: [1, 2]},
    method: 'GET',
    path: '/cards',
    query: {
      query: 'A card',
      member_ids: '5,6',
      states: '1,2',
      limit: '25',
      version: '2',
    },
    response: {result: [cardFixture], position: 'cursor-2'},
  },
  {
    name: 'get_card',
    args: card,
    method: 'GET',
    path: '/cards/10',
    response: cardFixture,
  },
  {
    name: 'create_card',
    args: {title: 'A card', board_id: 2, properties: {id_7: 'initial'}},
    method: 'POST',
    path: '/cards',
    body: {title: 'A card', board_id: 2, properties: {id_7: 'initial'}},
    response: cardFixture,
  },
  {
    name: 'update_card',
    args: {...card, changes: {description: null, asap: false}},
    method: 'PATCH',
    path: '/cards/10',
    body: {description: null, asap: false},
    response: {...cardFixture, description: null, asap: false},
  },
  {
    name: 'move_card',
    args: {...card, board_id: 2, column_id: 3, lane_id: 4},
    method: 'PATCH',
    path: '/cards/10',
    body: {board_id: 2, column_id: 3, lane_id: 4},
    response: cardFixture,
  },
  {
    name: 'archive_card',
    args: card,
    method: 'PATCH',
    path: '/cards/10',
    body: {condition: 2},
    response: {...cardFixture, condition: 2, archived: true},
  },
  {
    name: 'restore_card',
    args: card,
    method: 'PATCH',
    path: '/cards/10',
    body: {condition: 1},
    response: cardFixture,
  },
  {
    name: 'delete_card',
    args: card,
    method: 'DELETE',
    path: '/cards/10',
    response: cardFixture,
  },
  {
    name: 'list_comments',
    args: card,
    method: 'GET',
    path: '/cards/10/comments',
    response: [{id: 6, text: 'Comment'}],
  },
  {
    name: 'add_comment',
    args: {...card, text: 'Comment'},
    method: 'POST',
    path: '/cards/10/comments',
    body: {text: 'Comment'},
    response: {id: 6, text: 'Comment'},
  },
  {
    name: 'update_comment',
    args: {...card, comment_id: 6, text: 'Edited'},
    method: 'PATCH',
    path: '/cards/10/comments/6',
    body: {text: 'Edited'},
    response: {id: 6, text: 'Edited'},
  },
  {
    name: 'delete_comment',
    args: {...card, comment_id: 6},
    method: 'DELETE',
    path: '/cards/10/comments/6',
    response: {id: 6},
  },
  {
    name: 'list_card_members',
    args: card,
    method: 'GET',
    path: '/cards/10/members',
    response: [{id: 9, user_id: 5, type: 1}],
  },
  {
    name: 'add_card_member',
    args: {...card, user_id: 5},
    method: 'POST',
    path: '/cards/10/members',
    body: {user_id: 5},
    response: {id: 9, full_name: 'User', type: 1},
  },
  {
    name: 'update_card_member_role',
    args: {...card, member_id: 9, type: 2},
    method: 'PATCH',
    path: '/cards/10/members/9',
    body: {type: 2},
    response: {id: 9, type: 2},
  },
  {
    name: 'remove_card_member',
    args: {...card, member_id: 9},
    method: 'DELETE',
    path: '/cards/10/members/9',
    response: {id: 9},
  },
  {
    name: 'list_card_tags',
    args: card,
    method: 'GET',
    path: '/cards/10/tags',
    response: [{id: 12, tag_id: 11, name: 'Tag'}],
  },
  {
    name: 'add_card_tag',
    args: {...card, name: 'Tag'},
    method: 'POST',
    path: '/cards/10/tags',
    body: {name: 'Tag'},
    response: {id: 11, name: 'Tag'},
  },
  {
    name: 'remove_card_tag',
    args: {...card, tag_id: 11},
    method: 'DELETE',
    path: '/cards/10/tags/11',
    response: {id: 11},
  },
  {
    name: 'list_checklists',
    args: card,
    method: 'GET',
    path: '/cards/10',
    response: cardFixture,
  },
  {
    name: 'get_checklist',
    args: checklist,
    method: 'GET',
    path: '/cards/10/checklists/8',
    response: {id: 8, name: 'Tasks', items: []},
  },
  {
    name: 'create_checklist',
    args: {...card, name: 'Tasks'},
    method: 'POST',
    path: '/cards/10/checklists',
    body: {name: 'Tasks'},
    response: {id: 8, name: 'Tasks'},
  },
  {
    name: 'update_checklist',
    args: {...checklist, changes: {name: 'New'}},
    method: 'PATCH',
    path: '/cards/10/checklists/8',
    body: {name: 'New'},
    response: {id: 8, name: 'New'},
  },
  {
    name: 'delete_checklist',
    args: checklist,
    method: 'DELETE',
    path: '/cards/10/checklists/8',
    response: {id: 8},
  },
  {
    name: 'add_checklist_item',
    args: {...checklist, text: 'Task', checked: false},
    method: 'POST',
    path: '/cards/10/checklists/8/items',
    body: {text: 'Task', checked: false},
    response: {id: 13, text: 'Task', checked: false},
  },
  {
    name: 'update_checklist_item',
    args: {
      ...checklist,
      item_id: 13,
      changes: {checked: true, responsible_id: null},
    },
    method: 'PATCH',
    path: '/cards/10/checklists/8/items/13',
    body: {checked: true, responsible_id: null},
    response: {id: 13, checked: true, responsible_id: null},
  },
  {
    name: 'delete_checklist_item',
    args: {...checklist, item_id: 13},
    method: 'DELETE',
    path: '/cards/10/checklists/8/items/13',
    response: {id: 13},
  },
  {
    name: 'list_custom_properties',
    args: {query: 'Priority'},
    method: 'GET',
    path: '/company/custom-properties',
    query: {...page, query: 'Priority'},
    response: [{id: 7, name: 'Priority', type: 'select'}],
  },
  {
    name: 'get_custom_property',
    args: {property_id: 7},
    method: 'GET',
    path: '/company/custom-properties/7',
    response: {id: 7, name: 'Priority', type: 'select'},
  },
  {
    name: 'list_select_values',
    args: {property_id: 7},
    method: 'GET',
    path: '/company/custom-properties/7/select-values',
    query: page,
    response: [{id: 14, value: 'High'}],
  },
  {
    name: 'list_catalog_values',
    args: {property_id: 7},
    method: 'GET',
    path: '/company/custom-properties/7/catalog-values',
    query: page,
    response: [{id: 14, value: {name: 'Entry'}}],
  },
  {
    name: 'list_custom_directories',
    args: {},
    method: 'GET',
    path: '/company/custom-directories',
    query: {...page, include_fields: 'true'},
    response: [{id: directoryId, name: 'Directory', fields: []}],
  },
  {
    name: 'list_custom_directory_records',
    args: {directory_id: directoryId},
    method: 'GET',
    path: `/company/custom-directories/${directoryId}/records`,
    query: {...page, include_values: 'true'},
    response: [{id: directoryId, display_value: 'Entry', values: []}],
  },
  {
    name: 'set_card_properties',
    args: {...card, properties: {id_7: [14], id_8: null}},
    method: 'PATCH',
    path: '/cards/10',
    body: {properties: {id_7: [14], id_8: null}},
    response: {...cardFixture, properties: {id_7: [14]}},
  },
];
